import 'package:flutter/material.dart';

import '../models/category.dart';
import '../models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Hamburgers',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'German',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Asian',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'French',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.teal,
  ),
];

const DUMMY_MEALS = const [
  Meal(
      id: 'm1',
      categories: [
        'c1',
        'c2',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/52e4d5454b51ad14f1dc8460da2932761239d8ed525277_640.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c1',
        'c2',
        'c3',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c1',
        'c4',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c1',
        'c2',
        'c4',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://images.pexels.com/photos/769969/pexels-photo-769969.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c2',
        'c3',
        'c5',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c3',
        'c4',
        'c6',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://images.pexels.com/photos/769969/pexels-photo-769969.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c1',
        'c3',
        'c7',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c1',
        'c2',
        'c4',
        'c3',
        'c5',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c6',
        'c9',
        'c8',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://images.pexels.com/photos/769969/pexels-photo-769969.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c10',
        'c7',
        'c8',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c7',
        'c8',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c9',
        'c10',
        'c5',
        'c6',
        'c7',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c3',
        'c5',
        'c8',
        'c9',
        'c10',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm1',
      categories: [
        'c4',
        'c3',
        'c8',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://pixabay.com/get/57e3dc414855ae14f6d1867dda35367b1d38d8e35b527941_1920.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
];
