import 'package:flutter/material.dart';

import '../models/category.dart';
import '../models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Hamburgers',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'German',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Asian',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'French',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.teal,
  ),
];

const DUMMY_MEALS = const [
  Meal(
      id: 'm1',
      categories: [
        'c1',
        'c2',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: true,
      isLactoseFree: true,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm2',
      categories: [
        'c1',
        'c2',
        'c3',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm3',
      categories: [
        'c1',
        'c4',
      ],
      titile: 'Spaghetti without Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: true,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: false),
  Meal(
      id: 'm4',
      categories: [
        'c1',
        'c2',
        'c4',
      ],
      titile: 'Pizza',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://images.pexels.com/photos/769969/pexels-photo-769969.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: true,
      isVegan: false,
      isVegetarian: true),
  Meal(
      id: 'm5',
      categories: [
        'c2',
        'c3',
        'c5',
      ],
      titile: 'Burger',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: true,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm6',
      categories: [
        'c3',
        'c4',
        'c6',
      ],
      titile: 'Hamberger',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://images.pexels.com/photos/769969/pexels-photo-769969.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm7',
      categories: [
        'c1',
        'c3',
        'c7',
      ],
      titile: 'Momos',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: true,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm8',
      categories: [
        'c1',
        'c2',
        'c4',
        'c3',
        'c5',
      ],
      titile: 'Salsa',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: true,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: true),
  Meal(
      id: 'm9',
      categories: [
        'c6',
        'c9',
        'c8',
      ],
      titile: 'Cahumin',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://images.pexels.com/photos/769969/pexels-photo-769969.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: true,
      isVegan: false,
      isVegetarian: true),
  Meal(
      id: 'm10',
      categories: [
        'c10',
        'c7',
        'c8',
      ],
      titile: 'Toast with Drink',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: true,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm11',
      categories: [
        'c7',
        'c8',
      ],
      titile: 'Chaat Paapdi',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: false),
  Meal(
      id: 'm12',
      categories: [
        'c9',
        'c10',
        'c5',
        'c6',
        'c7',
      ],
      titile: 'Allo Tikki',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: false,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm13',
      categories: [
        'c3',
        'c5',
        'c8',
        'c9',
        'c10',
      ],
      titile: 'Spaghetti with Tomato Sauce',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: true,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: true),
  Meal(
      id: 'm14',
      categories: [
        'c4',
        'c3',
        'c8',
      ],
      titile: 'Samosa',
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      imageUrl:
          'https://www.efty.be/fondamental/wp-content/uploads/2015/08/Spag.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Table Spoon of Olive Oil',
        '1 Onion',
        '250 Spaghetti',
        'Spices',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomamtoes and onion in small pieces',
        'Boil Some Water - add some salt once it boils.',
        'put the spaghetti into the boiling water - they should be done so for atleast 10 minutes',
        'In the meanTime, Heaten up the Olive oil and add some chopped onion in the heaten oil.',
        'After 2 minutes , add the tomato pieces , salt , peper and your boiled Spaghetti to it then after a minute',
        'Add the sauce once the spaghetti are done',
        'Feel free to add some cheese to the finished Dish.'
      ],
      duration: 20,
      isGluttenFree: true,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
];
